-- Query 1 
-- What was wrong was the City is not a column in the orders table.It's stored in the customers table,
-- so i needed to JOIN the two tables.
-- Business meaning: Shows how many orders come from each city, helping understand customer activity by location.
SELECT c.city, COUNT(*) AS order_count
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id
GROUP BY c.city;    

-- Query 2 
-- What was wrong was product_name and price are not stored in the orders table.
-- They are stored in the products table, so I needed to JOIN the products table and calculate revenue correctly.
-- Business meaning: Shows revenue generated by each product from completed orders, helping identify top-selling products.
SELECT p.product_name, SUM(o.quantity * p.price) AS revenue
FROM orders o
JOIN products p  ON o.product_id = p.product_id
WHERE o.status = 'completed'
GROUP BY p.product_name;

-- Query 3
-- There was a semicolon at Group BY status so i just had to remove it.
-- Business meaning: Shows the number of orders by status, helping track completed, pending, and cancelled orders.
SELECT status, COUNT(*) AS order_count
FROM orders
GROUP BY status
ORDER BY order_count DESC;

-- Query 4
-- What was wrong was price is not stored in the orders table.
-- I needed to JOIN the products table to get the price and calculate the total amount.
-- Business meaning: Calculates the total value of each order to understand individual order revenue.
SELECT o.order_id, o.quantity, p.price,
 o.quantity * p.price AS total_amount
FROM orders o JOIN products p on o.product_id = p.product_id;

-- Query 5
-- What was wrong was category is not stored in the orders table.
-- I needed to JOIN the products table using product_id to get the category and calculate the total quantity.
-- Business meaning: Shows how many products were sold from each category, helping analyze category performance.
SELECT p.category, SUM(quantity) AS total_quantity
FROM orders o JOIN products p ON p.product_id = o.product_id
WHERE o.status = 'completed'
GROUP BY category;

-- Query 6 
-- Business meaning: Calculates the total revenue from all orders to measure overall sales performance.
SELECT SUM(quantity * price) AS total_revenue
FROM orders
JOIN products ON orders.product_id = products.product_id;

-- Query 7
-- I just changed the order becuase, the HAVING was was before the GROUP BY 
-- and a query cant start with Having
-- Business meaning: Finds customers who placed multiple orders, helping identify repeat customers.
SELECT customer_id, COUNT(*) AS order_count 
FROM orders 
GROUP BY customer_id
HAVING COUNT(*) > 1;

-- Query 8 
-- What was wrong was the JOIN was missing the connection condition between the two tables.
-- I needed to use customer_id to match orders with customers and get the customer name correctly.
-- Business meaning: Connects orders with customer information to identify who placed each order.
SELECT orders.order_id, customers.customer_name
FROM orders
JOIN customers on orders.customer_id = customers.customer_id;

-- Query 9 
-- What was wrong was the JOIN condition connected customer_id with product_id.
-- I needed to JOIN using product_id and use table aliases correctly.
-- Business meaning: Connects orders with product details to analyze which products were purchased.
SELECT o.customer_id,p.product_id,p.price
FROM orders o
JOIN products p ON o.product_id = p.product_id;

-- Query 10
-- What was wrong was the query was showing completed orders, which count as revenue.
-- I needed to filter pending and cancelled orders instead.
-- Business meaning: Shows orders that should not be included in revenue calculations to avoid incorrect sales reporting.
SELECT *
FROM orders
WHERE status != 'completed';


